# Generated by Django 4.2 on 2023-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_organizer_type_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participantsLimit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
