# Generated by Django 4.2 on 2023-04-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_participantslimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='zip',
            field=models.CharField(default='3930', max_length=10),
        ),
    ]
