# Generated by Django 4.2 on 2023-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_locationcomment_locationrating_delete_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rating',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
