# Generated by Django 4.2 on 2023-05-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_event_enddate_remove_event_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='user',
        ),
    ]
