# Generated by Django 4.2 on 2023-05-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_organizer_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='lan',
        ),
    ]
