# Generated by Django 4.2 on 2023-05-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_startdate_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participantsLimit',
        ),
    ]
