# Generated by Django 4.2 on 2023-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='locationcomment',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='locationrating',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
