# Generated by Django 4.2 on 2023-05-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_event_user_event_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationrating',
            name='user',
        ),
    ]
